display_location:
  type: enum
  default: "Both"
  choices:
    - Top
    - Bottom
    - Both
  description: "Where should the topic timer appear?"

enabled_categories:
  type: list
  list_type: category
  default: ""
  description: "Choose categories where the topic timer location will be modified. Leave empty to apply to all categories."
