display_location:
  type: enum
  default: "Both"
  choices:
    - Top
    - Bottom
    - Both
  description: "Where should the topic timer appear?"

use_parent_for_link:
  type: bool
  default: false
  description: "Use parent name for category link in topic timer banner?"

allowed_category_ids:
  type: string
  default: ""
  description: "Comma-separated list of category IDs where topic timers will be displayed. Leave empty to show in all categories."
