display_location:
  type: enum
  default: "both"
  choices:
    - top
    - bottom
    - both
  description: "Where should the topic timer appear?"

link_to_parent_category:
  type: bool
  default: false
  description: "Use parent category link for publish timers"

topic_label_override:
  type: string
  default: ""
  description: "Replace the word 'topic' in the publish timer message (e.g., guide, announcement)"
