display_location:
  type: enum
  default: "Both"
  choices:
    - Top
    - Bottom
    - Both
  description: "Where should the topic timer appear?"

use_parent_for_link:
  type: bool
  default: false
  description: "Use parent name for category link in topic timer banner?"

enabled_category_ids:
  type: list
  default: ""
  description: "Only apply to topics in these category IDs (one per line)"

