display_location:
  type: enum
  default: "Both"
  choices:
    - Both
    - Top
    - Bottom
  description: "Where should the topic timer appear?"

link_to_parent_category:
  type: bool
  default: false
  description: "For publish timers, link to the parent category instead of the one it's publishing to."
