display_location:
  type: enum
  default: "Both"
  choices:
    - Top
    - Bottom
    - Both
  description: "Where should the topic timer appear?"

link_to_parent_category:
  type: bool
  default: false
  description: "Use parent category link for publish timers?"
